# Generated by Django 3.2.7 on 2021-10-03 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0002_gamer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamer',
            name='gamer_name',
        ),
        migrations.AddField(
            model_name='gamer',
            name='gamerName',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bet',
            name='author',
            field=models.CharField(max_length=30),
        ),
    ]
