# Generated by Django 3.2.7 on 2021-10-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0004_auto_20211003_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bet',
            field=models.IntegerField(default=0),
        ),
    ]
